---
# Source: vector/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-vector-headless
  labels:
    helm.sh/chart: vector-0.30.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: Agent
    app.kubernetes.io/version: "0.35.0-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
  annotations:
spec:
  clusterIP: None
  ports:
    - name: datadog-agent
      port: 8282
      protocol: TCP
    - name: fluent
      port: 24224
      protocol: TCP
    - name: logstash
      port: 5044
      protocol: TCP
    - name: splunk-hec
      port: 8080
      protocol: TCP
    - name: statsd
      port: 8125
      protocol: TCP
    - name: syslog
      port: 9000
      protocol: TCP
    - name: vector
      port: 6000
      protocol: TCP
    - name: prom-exporter
      port: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: Agent
  type: ClusterIP
